# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.flying_idle.frame dummy
scoreboard objectives add aj.flap.frame dummy
scoreboard objectives add aj.dive.frame dummy
scoreboard objectives add aj.attack.frame dummy