# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.block.frame matches 7.. run scoreboard players set @s aj.block.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.block.frame
execute at @s run function animated_java:ghost_knight/animations/block/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.block.frame 1