# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mage_hunter.node.chest] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_chest set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mage_hunter.node.cape] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_cape set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mage_hunter.node.saber] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_saber set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mage_hunter.node.right_forearm] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_forearm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mage_hunter.node.right_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mage_hunter.node.short_sword] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_short_sword set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mage_hunter.node.left_forearm] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_forearm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mage_hunter.node.left_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mage_hunter.node.torso] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_torso set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mage_hunter.node.right_dress] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_dress set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mage_hunter.node.left_dress] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_dress set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mage_hunter.node.lower_right_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_lower_right_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mage_hunter.node.right_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mage_hunter.node.lower_left_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_lower_left_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mage_hunter.node.left_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mage_hunter.node.waist] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_waist set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mage_hunter.node.pony_tail] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_pony_tail set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mage_hunter.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head set from storage aj:uuid main.out