# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:cutter/root/zzz/on_tick/select_locator_particle with entity @s data.locators.particle
function animated_java:cutter/root/zzz/on_tick/select_locator_particle2 with entity @s data.locators.particle2