# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.hellfire.root] run return 0
execute if entity @s[tag=aj.hellfire.animation.start.playing] run function animated_java:hellfire/animations/start/zzz/on_tick
execute on passengers run rotate @s ~ ~