# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '5e8e7443f104f13793355f071572e2ab5ffffb75214aac5a1a082ffec7b847cf'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack