# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '9c8a862dd5c5fb266dc136246955513b402a49c263b8633cb5494930f9aa09f4'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack