# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players remove @s aj.tween_duration 1
execute if score @s aj.tween_duration matches 1.. run return 1
execute if score @s aj.tween_duration matches 0 on passengers run data modify entity @s interpolation_duration set value 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.cast3.frame
function animated_java:lich/animations/cast3/zzz/apply_frame with storage aj:temp args
execute if score @s aj.cast3.frame matches 32.. run return run function animated_java:lich/animations/cast3/pause
scoreboard players add @s aj.cast3.frame 1