# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.ruin_star.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'ruin_star', 'function_path': 'animated_java:ruin_star/animations/expand/stop'}
tag @s remove aj.ruin_star.animation.expand.playing
scoreboard players set @s aj.expand.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:ruin_star/animations/expand/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only