# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:lich/root/zzz/on_tick/select_locator_hitbox with entity @s data.locators.hitbox
function animated_java:lich/root/zzz/on_tick/select_locator_hitbox2 with entity @s data.locators.hitbox2