# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:lich/root/zzz/on_tick/select_locator_scythe_blade with entity @s data.locators.scythe_blade
function animated_java:lich/root/zzz/on_tick/select_locator_scythe_pole with entity @s data.locators.scythe_pole