# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.wizard.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'wizard', 'function_path': 'animated_java:wizard/variants/hurt/apply'}
execute on passengers if entity @s[tag=aj.wizard.bone.hat] run function animated_java:wizard/variants/hurt/zzz/apply_to_bone_hat
execute on passengers if entity @s[tag=aj.wizard.bone.nose] run function animated_java:wizard/variants/hurt/zzz/apply_to_bone_nose
execute on passengers if entity @s[tag=aj.wizard.bone.head] run function animated_java:wizard/variants/hurt/zzz/apply_to_bone_head
execute on passengers if entity @s[tag=aj.wizard.bone.body] run function animated_java:wizard/variants/hurt/zzz/apply_to_bone_body
execute on passengers if entity @s[tag=aj.wizard.bone.arms_flipped] run function animated_java:wizard/variants/hurt/zzz/apply_to_bone_arms_flipped
execute on passengers if entity @s[tag=aj.wizard.bone.arms_rotation] run function animated_java:wizard/variants/hurt/zzz/apply_to_bone_arms_rotation
execute on passengers if entity @s[tag=aj.wizard.bone.left_arm] run function animated_java:wizard/variants/hurt/zzz/apply_to_bone_left_arm
execute on passengers if entity @s[tag=aj.wizard.bone.wand] run function animated_java:wizard/variants/hurt/zzz/apply_to_bone_wand
execute on passengers if entity @s[tag=aj.wizard.bone.right_arm] run function animated_java:wizard/variants/hurt/zzz/apply_to_bone_right_arm
execute on passengers if entity @s[tag=aj.wizard.bone.left_leg] run function animated_java:wizard/variants/hurt/zzz/apply_to_bone_left_leg
execute on passengers if entity @s[tag=aj.wizard.bone.right_leg] run function animated_java:wizard/variants/hurt/zzz/apply_to_bone_right_leg
return 1