# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg7] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg8] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg8 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg9] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg9 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg10] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg10 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg11] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg11 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg12] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg12 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg13] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg13 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg14] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg14 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg15] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg15 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg16] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg16 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg17] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg17 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg18] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg18 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg19] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg19 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg20] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg20 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg21] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg21 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg22] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg22 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg23] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg23 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg24] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg24 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg25] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg25 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg26] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg26 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg27] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg27 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg28] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg28 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg29] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg29 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg30] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg30 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg31] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg31 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg32] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg32 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg33] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg33 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg34] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg34 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lightning.node.seg35] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_seg35 set from storage aj:uuid main.out