# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function magic:mobs/lich/atk/end_attack
function magic:mobs/lich/atk/resume_movement
scoreboard players operation #magicSearch magic.id = @s magic.id
scoreboard players remove @n[type=wither_skeleton,predicate=magic:match_id,distance=..5] magic.atkCD 15