# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.ghost_knight.root] run return 0
execute if entity @s[tag=aj.ghost_knight.animation.spawn.playing] run function animated_java:ghost_knight/animations/spawn/zzz/on_tick
execute if entity @s[tag=aj.ghost_knight.animation.idle.playing] run function animated_java:ghost_knight/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.ghost_knight.animation.move.playing] run function animated_java:ghost_knight/animations/move/zzz/on_tick
execute if entity @s[tag=aj.ghost_knight.animation.dodge_back.playing] run function animated_java:ghost_knight/animations/dodge_back/zzz/on_tick
execute if entity @s[tag=aj.ghost_knight.animation.swing.playing] run function animated_java:ghost_knight/animations/swing/zzz/on_tick
execute if entity @s[tag=aj.ghost_knight.animation.thrust.playing] run function animated_java:ghost_knight/animations/thrust/zzz/on_tick
execute if entity @s[tag=aj.ghost_knight.animation.block.playing] run function animated_java:ghost_knight/animations/block/zzz/on_tick
execute if entity @s[tag=aj.ghost_knight.animation.block_hit.playing] run function animated_java:ghost_knight/animations/block_hit/zzz/on_tick
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:ghost_knight/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~