# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.wizard.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'wizard', 'function_path': 'animated_java:wizard/animations/aggro/next_frame'}
execute if score @s aj.aggro.frame matches 2.. run scoreboard players set @s aj.aggro.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.aggro.frame
execute at @s run function animated_java:wizard/animations/aggro/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.aggro.frame 1