# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound minecraft:entity.wind_charge.wind_burst master @a ~ ~ ~ 1 0.6
function magic:mobs/hunter/motion/store_rotation