# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.mage_hunter.root] run return 0
execute on passengers if entity @s[tag=aj.mage_hunter.data] unless data entity @s {data:{rigHash: '3ff7b16f9438736c5f167bd7f51764b658e6236267ad8c889746f70668319881'}} on vehicle run function animated_java:mage_hunter/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1