# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.mage_hunter.root] run return 0
execute on passengers if entity @s[tag=aj.mage_hunter.data] unless data entity @s {data:{rigHash: '72f1a4fc61709adc7f6c39813558d3474e0aceff006ccffb061e55e688ebcc19'}} on vehicle run function animated_java:mage_hunter/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1