# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.mage_hunter.root] run return 0
execute on passengers if entity @s[tag=aj.mage_hunter.data] unless data entity @s {data:{rigHash: 'bc06493d4b39a6c220dd2a713fed690a377b0103a785b784574977c7538725c7'}} on vehicle run function animated_java:mage_hunter/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1