# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.mage_hunter.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.mage_hunter.animation.still.playing] run function animated_java:mage_hunter/animations/still/zzz/on_tick
execute if entity @s[tag=aj.mage_hunter.animation.stagger.playing] run function animated_java:mage_hunter/animations/stagger/zzz/on_tick
execute if entity @s[tag=aj.mage_hunter.animation.walk.playing] run function animated_java:mage_hunter/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.mage_hunter.animation.slash.playing] run function animated_java:mage_hunter/animations/slash/zzz/on_tick
execute if entity @s[tag=aj.mage_hunter.animation.double_slash.playing] run function animated_java:mage_hunter/animations/double_slash/zzz/on_tick
execute if entity @s[tag=aj.mage_hunter.animation.cross_slash.playing] run function animated_java:mage_hunter/animations/cross_slash/zzz/on_tick
execute if entity @s[tag=aj.mage_hunter.animation.thrust1.playing] run function animated_java:mage_hunter/animations/thrust1/zzz/on_tick
execute if entity @s[tag=aj.mage_hunter.animation.thrust2.playing] run function animated_java:mage_hunter/animations/thrust2/zzz/on_tick
execute if entity @s[tag=aj.mage_hunter.animation.lunge1.playing] run function animated_java:mage_hunter/animations/lunge1/zzz/on_tick
execute if entity @s[tag=aj.mage_hunter.animation.side_slash1.playing] run function animated_java:mage_hunter/animations/side_slash1/zzz/on_tick
execute if entity @s[tag=aj.mage_hunter.animation.side_slash2.playing] run function animated_java:mage_hunter/animations/side_slash2/zzz/on_tick
execute if entity @s[tag=aj.mage_hunter.animation.dodge_back.playing] run function animated_java:mage_hunter/animations/dodge_back/zzz/on_tick
execute if entity @s[tag=aj.mage_hunter.animation.dodge_front.playing] run function animated_java:mage_hunter/animations/dodge_front/zzz/on_tick
execute if entity @s[tag=aj.mage_hunter.animation.dodge_right.playing] run function animated_java:mage_hunter/animations/dodge_right/zzz/on_tick
execute if entity @s[tag=aj.mage_hunter.animation.dodge_left.playing] run function animated_java:mage_hunter/animations/dodge_left/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~