# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.lich.root] run return 0
execute on passengers if entity @s[tag=aj.lich.data] unless data entity @s {data:{rigHash: 'b165637d47b9f18aacedee5b740826e7f6d4794c762ed234378905fdf9adf339'}} on vehicle run function animated_java:lich/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1