# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.lich.root] run return 0
execute on passengers if entity @s[tag=aj.lich.data] unless data entity @s {data:{rigHash: '274b5996b1ea2e12e6719933945ceb5dc0f16dca12b493dbb3724f6cafc88538'}} on vehicle run function animated_java:lich/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1