# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.lich.root] run return 0
execute on passengers if entity @s[tag=aj.lich.data] unless data entity @s {data:{rigHash: 'ad02839a0fced8bc428dcddfc8047a7e93c71c52740dac5ed9ef364fce27dfd0'}} on vehicle run function animated_java:lich/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1