# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.raptor.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'raptor', 'function_path': 'animated_java:raptor/animations/dive/play'}
tag @s add aj.raptor.animation.dive.playing
scoreboard players set @s aj.dive.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:raptor/animations/dive/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only