# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.mage_hunter.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'mage_hunter', 'function_path': 'animated_java:mage_hunter/animations/slash/play'}
tag @s add aj.mage_hunter.animation.slash.playing
scoreboard players set @s aj.slash.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:mage_hunter/animations/slash/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only