# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.lich.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'lich', 'function_path': 'animated_java:lich/animations/fake_die/stop'}
tag @s remove aj.lich.animation.fake_die.playing
scoreboard players set @s aj.fake_die.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:lich/animations/fake_die/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only