# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @p[distance=..3.5] run scoreboard players set #magicMotion magic.temp 1
execute unless entity @p[distance=..3.5] run scoreboard players set #magicMotion magic.temp 2
function magic:mobs/hunter/motion/launch