# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function magic:mobs/hunter/motion/lock_rotation
execute on vehicle run function magic:mobs/hunter/atk/double_slash_chain