# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function magic:mobs/hunter/atk/end_attack
execute on vehicle run scoreboard players add @s magic.atkCD 30