# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.ruin_star.root] run return 0
execute on passengers if entity @s[tag=aj.ruin_star.data] unless data entity @s {data:{rigHash: 'b03637b1a4256cd5f6ec68a2d9ff16622f0ec2d360ff5d6d852838a5133b712c'}} on vehicle run function animated_java:ruin_star/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1