# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.ruin_star.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.ruin_star.animation.spin.playing] run function animated_java:ruin_star/animations/spin/zzz/on_tick
execute if entity @s[tag=aj.ruin_star.animation.expand.playing] run function animated_java:ruin_star/animations/expand/zzz/on_tick
execute if entity @s[tag=aj.ruin_star.animation.shrink.playing] run function animated_java:ruin_star/animations/shrink/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~