# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lich.node.hair_side] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_hair_side set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lich.node.hair_side1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_hair_side1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lich.node.beard] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_beard set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lich.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lich.node.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lich.node.left4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lich.node.left3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lich.node.aura] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_aura set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lich.node.scythe] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_scythe set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lich.node.right2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lich.node.right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lich.node.left_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lich.node.right_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_leg set from storage aj:uuid main.out