# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
summon minecraft:marker ^-0.4123148334 ^1.0594554182 ^1.1138912884 {Tags:["aj.global.bone.bone1.decendant","aj.global.bone.bone1.decendant.locator","aj.global.bone.bone1.tree","aj.global.bone.right1.decendant","aj.global.bone.right1.decendant.locator","aj.global.bone.right1.tree","aj.global.bone.right2.decendant","aj.global.bone.right2.decendant.locator","aj.global.bone.right2.tree","aj.global.bone.right_arm.decendant","aj.global.bone.right_arm.decendant.locator","aj.global.bone.right_arm.tree","aj.global.bone.scythe.child","aj.global.bone.scythe.child.locator","aj.global.bone.scythe.decendant","aj.global.bone.scythe.decendant.locator","aj.global.bone.scythe.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.hitbox","aj.lich.bone.bone1.decendant","aj.lich.bone.bone1.decendant.locator","aj.lich.bone.bone1.tree","aj.lich.bone.right1.decendant","aj.lich.bone.right1.decendant.locator","aj.lich.bone.right1.tree","aj.lich.bone.right2.decendant","aj.lich.bone.right2.decendant.locator","aj.lich.bone.right2.tree","aj.lich.bone.right_arm.decendant","aj.lich.bone.right_arm.decendant.locator","aj.lich.bone.right_arm.tree","aj.lich.bone.scythe.child","aj.lich.bone.scythe.child.locator","aj.lich.bone.scythe.decendant","aj.lich.bone.scythe.decendant.locator","aj.lich.bone.scythe.tree","aj.lich.entity","aj.lich.locator","aj.lich.locator.hitbox","aj.lich.node","aj.lich.node.hitbox","aj.new"]}
execute as @n[ type=minecraft:marker, tag=aj.new, tag=aj.lich.locator.hitbox, distance=..3 ] run function animated_java:lich/zzz/summon/as_data_entity/as_locator/hitbox
data modify entity @s data.uuids.locator_hitbox set from storage aj:uuid main.out
data modify entity @s data.locators.hitbox.uuid set from storage aj:uuid main.out
summon minecraft:marker ^-0.5691132931 ^0.3521832726 ^1.3080055722 {Tags:["aj.global.bone.bone1.decendant","aj.global.bone.bone1.decendant.locator","aj.global.bone.bone1.tree","aj.global.bone.right1.decendant","aj.global.bone.right1.decendant.locator","aj.global.bone.right1.tree","aj.global.bone.right2.decendant","aj.global.bone.right2.decendant.locator","aj.global.bone.right2.tree","aj.global.bone.right_arm.decendant","aj.global.bone.right_arm.decendant.locator","aj.global.bone.right_arm.tree","aj.global.bone.scythe.child","aj.global.bone.scythe.child.locator","aj.global.bone.scythe.decendant","aj.global.bone.scythe.decendant.locator","aj.global.bone.scythe.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.hitbox2","aj.lich.bone.bone1.decendant","aj.lich.bone.bone1.decendant.locator","aj.lich.bone.bone1.tree","aj.lich.bone.right1.decendant","aj.lich.bone.right1.decendant.locator","aj.lich.bone.right1.tree","aj.lich.bone.right2.decendant","aj.lich.bone.right2.decendant.locator","aj.lich.bone.right2.tree","aj.lich.bone.right_arm.decendant","aj.lich.bone.right_arm.decendant.locator","aj.lich.bone.right_arm.tree","aj.lich.bone.scythe.child","aj.lich.bone.scythe.child.locator","aj.lich.bone.scythe.decendant","aj.lich.bone.scythe.decendant.locator","aj.lich.bone.scythe.tree","aj.lich.entity","aj.lich.locator","aj.lich.locator.hitbox2","aj.lich.node","aj.lich.node.hitbox2","aj.new"]}
execute as @n[ type=minecraft:marker, tag=aj.new, tag=aj.lich.locator.hitbox2, distance=..4 ] run function animated_java:lich/zzz/summon/as_data_entity/as_locator/hitbox2
data modify entity @s data.uuids.locator_hitbox2 set from storage aj:uuid main.out
data modify entity @s data.locators.hitbox2.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lich.node.hair_side] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_hair_side set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lich.node.hair_side1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_hair_side1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lich.node.beard] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_beard set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lich.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lich.node.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lich.node.left4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lich.node.left3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lich.node.scythe] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_scythe set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lich.node.right2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lich.node.right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lich.node.left_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lich.node.right_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_leg set from storage aj:uuid main.out