# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.still.frame
scoreboard objectives remove aj.die.frame
scoreboard objectives remove aj.fake_die.frame
scoreboard objectives remove aj.pray.frame
scoreboard objectives remove aj.walk.frame
scoreboard objectives remove aj.dash.frame
scoreboard objectives remove aj.swing1.frame
scoreboard objectives remove aj.swing2.frame
scoreboard objectives remove aj.swing3.frame
scoreboard objectives remove aj.swing_flurry.frame
scoreboard objectives remove aj.ground_cutter.frame
scoreboard objectives remove aj.slam.frame
scoreboard objectives remove aj.cast1.frame
scoreboard objectives remove aj.cast2.frame
scoreboard objectives remove aj.cast3.frame
scoreboard objectives remove aj.shotgun.frame
scoreboard objectives remove aj.delayed_bomb.frame
scoreboard objectives remove aj.dodge_right.frame
scoreboard objectives remove aj.dodge_left.frame
tellraw @a [[{"text":"\n[","color":"gray"},{"text":"AJ","color":"aqua"},"] ",[{"text":"(from ","color":"gray","italic":true},"lich",")"]," -> "],{"text":"Successfully removed known animation scoreboard objectives.","color":"red"},{"text":"\nIf you have exported multiple times you may have to manually remove some objectives from previous exports manually, as Animated Java can only remove the latest export's objectives.","color":"gray","italic":true},["\n"]]