# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players set @s aj.dodge_back.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:ghost_knight/animations/dodge_back/zzz/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only