# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound minecraft:entity.player.attack.sweep master @a ~ ~ ~ 1.2 1.2
playsound minecraft:entity.player.attack.sweep master @a ~ ~ ~ 1.2 1.2
function magic:mobs/hunter/motion/lock_rotation
execute if entity @p[distance=..3.5] run scoreboard players set #magicMotion magic.temp 2
execute unless entity @p[distance=..3.5] run scoreboard players set #magicMotion magic.temp 3
function magic:mobs/hunter/motion/launch