# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players operation #magicSearch magic.id = @s magic.id
execute positioned ~-0.5 ~-0.5 ~-0.5 as @e[type=#magic:targets,predicate=!magic:match_id,dx=0,dy=0,dz=0] unless score @s magic.iframe matches 1.. run damage @s 34 player_attack