# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_wand) {transformation: [-1f,0f,0f,-0.3125f,0f,1f,0f,-1.3125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-1f,0f,0f,-0.3125f,0f,1f,0f,-0.75f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:dummy/animations/cast1/zzz/frames/20_root_commands