# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.shield.root] run return 0
execute on passengers if entity @s[tag=aj.shield.data] unless data entity @s {data:{rigHash: '0913514bb30a7e5b5b48060a779bcfc30c2eb83903bd87512e8b738e485e79bf'}} on vehicle run function animated_java:shield/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1