# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.shield.root] run return 0
execute on passengers if entity @s[tag=aj.shield.data] unless data entity @s {data:{rigHash: '8a5e4c5eeb0840850f04753004e5c56c61c74b9b3a0bc5bac978f598861d2aac'}} on vehicle run function animated_java:shield/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1