# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.shield.root] run return 0
execute on passengers if entity @s[tag=aj.shield.data] unless data entity @s {data:{rigHash: 'b605d271102114ab77f1f879e8438abb7d0a23f2329acb4ae09bebe8a2b69b26'}} on vehicle run function animated_java:shield/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1