# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.hellfire.node.block_display] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.block_display_block_display set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.hellfire.node.block_display1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.block_display_block_display1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.hellfire.node.block_display2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.block_display_block_display2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.hellfire.node.block_display3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.block_display_block_display3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.hellfire.node.block_display4] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.block_display_block_display4 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.hellfire.node.block_display5] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.block_display_block_display5 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.hellfire.node.block_display6] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.block_display_block_display6 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.hellfire.node.block_display7] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.block_display_block_display7 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.hellfire.node.block_display8] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.block_display_block_display8 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.hellfire.node.block_display9] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.block_display_block_display9 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.hellfire.node.block_display10] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.block_display_block_display10 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.hellfire.node.block_display11] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.block_display_block_display11 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.hellfire.node.block_display12] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.block_display_block_display12 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.hellfire.node.block_display13] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.block_display_block_display13 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.hellfire.node.block_display14] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.block_display_block_display14 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.hellfire.node.block_display15] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.block_display_block_display15 set from storage animated_java:gu out