# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.spin.frame matches 11.. run scoreboard players set @s aj.spin.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.spin.frame
execute at @s run function animated_java:sword_projectile/animations/spin/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.spin.frame 1