# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound minecraft:item.trident.throw master @a ~ ~ ~ 1.5 0.9
function magic:mobs/hunter/motion/lock_rotation
execute if entity @p[distance=..5] run scoreboard players set #magicMotion magic.temp 2
execute if entity @p[distance=5..8] run scoreboard players set #magicMotion magic.temp 3
execute unless entity @p[distance=..8] run scoreboard players set #magicMotion magic.temp 4
function magic:mobs/hunter/motion/launch