# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_right_leg1) {transformation: [-1f,0f,0f,-0.1562f,0f,0.766f,0.6428f,-0.1436f,0f,0.6428f,-0.766f,-0.3705f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-1f,0f,0f,-0.1562f,0f,0.766f,0.6428f,0f,0f,0.6428f,-0.766f,-0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_leg1) {transformation: [-1f,0f,0f,0.1563f,0f,0.766f,0.6428f,-0.1436f,0f,0.6428f,-0.766f,-0.3705f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_leg) {transformation: [-1f,0f,0f,0.1563f,0f,0.766f,0.6428f,0f,0f,0.6428f,-0.766f,-0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tail) {transformation: [-1f,0f,0f,-0.0312f,0f,1f,0f,0.125f,0f,0f,-1f,-0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9848f,0.1736f,0.2031f,0f,0.1736f,-0.9848f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing1) {transformation: [-1f,0f,0f,-1.0977f,0f,1f,0f,0.3164f,0f,0f,-1f,0.2187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-1f,0f,0f,-0.2653f,0f,1f,0f,0.3099f,0f,0f,-1f,-0.1179f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing1) {transformation: [-1f,0f,0f,1.0977f,0f,1f,0f,0.3164f,0f,0f,-1f,0.2188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-1f,0f,0f,0.2653f,0f,1f,0f,0.3099f,0f,0f,-1f,-0.1179f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0.0313f,0f,1f,0f,-0.0625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:raptor/animations/flap/zzz/frames/21_root_commands