# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score #rng magic.temp run random value 0..2
execute if score #rng magic.temp matches 0 run function animated_java:raptor/animations/flap/play