# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.lightning.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'lightning', 'function_path': 'animated_java:lightning/animations/strike/next_frame'}
execute if score @s aj.strike.frame matches 16.. run scoreboard players set @s aj.strike.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.strike.frame
execute at @s run function animated_java:lightning/animations/strike/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.strike.frame 1