# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:mage_hunter/root/zzz/on_tick/select_locator_body_hitbox with entity @s data.locators.body_hitbox
function animated_java:mage_hunter/root/zzz/on_tick/select_locator_saber_hitbox with entity @s data.locators.saber_hitbox
function animated_java:mage_hunter/root/zzz/on_tick/select_locator_short_sword_hitbox with entity @s data.locators.short_sword_hitbox