# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:mage_hunter/root/zzz/on_tick/select_locator_locator with entity @s data.locators.locator
function animated_java:mage_hunter/root/zzz/on_tick/select_locator_locator2 with entity @s data.locators.locator2
function animated_java:mage_hunter/root/zzz/on_tick/select_locator_locator3 with entity @s data.locators.locator3
function animated_java:mage_hunter/root/zzz/on_tick/select_locator_locator4 with entity @s data.locators.locator4
function animated_java:mage_hunter/root/zzz/on_tick/select_locator_locator5 with entity @s data.locators.locator5
function animated_java:mage_hunter/root/zzz/on_tick/select_locator_saber_hitbox with entity @s data.locators.saber_hitbox
function animated_java:mage_hunter/root/zzz/on_tick/select_locator_locator6 with entity @s data.locators.locator6
function animated_java:mage_hunter/root/zzz/on_tick/select_locator_locator7 with entity @s data.locators.locator7
function animated_java:mage_hunter/root/zzz/on_tick/select_locator_locator8 with entity @s data.locators.locator8
function animated_java:mage_hunter/root/zzz/on_tick/select_locator_locator9 with entity @s data.locators.locator9
function animated_java:mage_hunter/root/zzz/on_tick/select_locator_locator10 with entity @s data.locators.locator10
function animated_java:mage_hunter/root/zzz/on_tick/select_locator_short_sword_hitbox with entity @s data.locators.short_sword_hitbox