# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:mage_hunter/root/zzz/on_tick/select_locator_body_hitbox with entity @s data.locators.body_hitbox
function animated_java:mage_hunter/root/zzz/on_tick/select_locator_flame with entity @s data.locators.flame
function animated_java:mage_hunter/root/zzz/on_tick/select_locator_flame1 with entity @s data.locators.flame1
function animated_java:mage_hunter/root/zzz/on_tick/select_locator_flame2 with entity @s data.locators.flame2
function animated_java:mage_hunter/root/zzz/on_tick/select_locator_flame3 with entity @s data.locators.flame3
function animated_java:mage_hunter/root/zzz/on_tick/select_locator_flame4 with entity @s data.locators.flame4
function animated_java:mage_hunter/root/zzz/on_tick/select_locator_saber_hitbox with entity @s data.locators.saber_hitbox
function animated_java:mage_hunter/root/zzz/on_tick/select_locator_flame5 with entity @s data.locators.flame5
function animated_java:mage_hunter/root/zzz/on_tick/select_locator_flame6 with entity @s data.locators.flame6
function animated_java:mage_hunter/root/zzz/on_tick/select_locator_flame7 with entity @s data.locators.flame7
function animated_java:mage_hunter/root/zzz/on_tick/select_locator_flame8 with entity @s data.locators.flame8
function animated_java:mage_hunter/root/zzz/on_tick/select_locator_flame9 with entity @s data.locators.flame9
function animated_java:mage_hunter/root/zzz/on_tick/select_locator_short_sword_hitbox with entity @s data.locators.short_sword_hitbox