# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:wizard/zzz/summon/as_data_entity
execute if data storage aj:temp args.variant run function animated_java:wizard/zzz/summon/variant_arg/process with storage aj:temp args
function animated_java:wizard/set_default_pose
execute if data storage aj:temp args.animation run function animated_java:wizard/zzz/summon/animation_arg/process with storage aj:temp args
tp @s ~ ~ ~ ~ ~
execute at @s on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
function magic:mobs/wizard/setup_wizard
function animated_java:wizard/animations/still/play
execute at @s run function squidchant:mobs/wizard/summon_base
tag @s remove aj.new
execute on passengers run tag @s remove aj.new