# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:ghost_knight/animations/pause_all
tag @s add aj.ghost_knight.animation.swing.playing
scoreboard players set @s aj.swing.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:ghost_knight/animations/swing/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only