# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.raptor.root] run return 0
execute on passengers if entity @s[tag=aj.raptor.data] unless data entity @s {data:{rigHash: 'b960fd51b1aaa4eae748c0a076f641ea593485d935fc0d30afea62536df29302'}} on vehicle run function animated_java:raptor/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1