# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.raptor.root] run return 0
execute on passengers if entity @s[tag=aj.raptor.data] unless data entity @s {data:{rigHash: '84c8026f733f4d5a9d37c88af679ca6a75037bf11b81d8ec063ebfdd1abb5599'}} on vehicle run function animated_java:raptor/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1