# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.raptor.root] run return 0
execute on passengers if entity @s[tag=aj.raptor.data] unless data entity @s {data:{rigHash: '8a699ff40837442b9f01606413c0ba78b7f4e4e92b51a2e3c7e0eff7f820cf4e'}} on vehicle run function animated_java:raptor/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1