# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.raptor.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.raptor.animation.flying_idle.playing] run function animated_java:raptor/animations/flying_idle/zzz/on_tick
execute if entity @s[tag=aj.raptor.animation.flap.playing] run function animated_java:raptor/animations/flap/zzz/on_tick
execute if entity @s[tag=aj.raptor.animation.dive.playing] run function animated_java:raptor/animations/dive/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~