# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:ghost_knight/animations/idle/zzz/apply_frame {frame: 40}
scoreboard players add @s aj.idle.frame 1