# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.still.frame
scoreboard objectives remove aj.die.frame
scoreboard objectives remove aj.stagger.frame
scoreboard objectives remove aj.walk.frame
scoreboard objectives remove aj.transition_phase.frame
scoreboard objectives remove aj.slash.frame
scoreboard objectives remove aj.double_slash.frame
scoreboard objectives remove aj.cross_slash.frame
scoreboard objectives remove aj.thrust1.frame
scoreboard objectives remove aj.thrust2.frame
scoreboard objectives remove aj.lunge1.frame
scoreboard objectives remove aj.side_slash1.frame
scoreboard objectives remove aj.side_slash2.frame
scoreboard objectives remove aj.dodge_back.frame
scoreboard objectives remove aj.dodge_front.frame
scoreboard objectives remove aj.dodge_right.frame
scoreboard objectives remove aj.dodge_left.frame
tellraw @a [[{"text":"\n[","color":"gray"},{"text":"AJ","color":"aqua"},"] ",[{"text":"(from ","color":"gray","italic":true},"mage_hunter",")"]," -> "],{"text":"Successfully removed known animation scoreboard objectives.","color":"red"},{"text":"\nIf you have exported multiple times you may have to manually remove some objectives from previous exports manually, as Animated Java can only remove the latest export's objectives.","color":"gray","italic":true},["\n"]]