# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.lich.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'lich', 'function_path': 'animated_java:lich/animations/pause_all'}
tag @s remove aj.lich.animation.still.playing
tag @s remove aj.lich.animation.die.playing
tag @s remove aj.lich.animation.fake_die.playing
tag @s remove aj.lich.animation.walk.playing
tag @s remove aj.lich.animation.dash.playing
tag @s remove aj.lich.animation.pray.playing
tag @s remove aj.lich.animation.swing1.playing
tag @s remove aj.lich.animation.swing2.playing
tag @s remove aj.lich.animation.ground_cutter.playing
tag @s remove aj.lich.animation.slam.playing
tag @s remove aj.lich.animation.cast1.playing
tag @s remove aj.lich.animation.cast2.playing
tag @s remove aj.lich.animation.shotgun.playing
tag @s remove aj.lich.animation.delayed_bomb.playing
tag @s remove aj.lich.animation.dodge_right.playing
tag @s remove aj.lich.animation.dodge_left.playing