# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '7c7215a9e975124353e67f13c1c5a6eb36344ae922f11099318f8335e5ae68e6'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack