# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:hellfire rig_hash set value '3429a952c224ed4f4c3fcca072a69e4a3a21cc32c0947448653f9aa503aa4976'
scoreboard objectives add aj.start.frame dummy