# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.lich.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'lich', 'function_path': 'animated_java:lich/variants/default/apply'}
execute on passengers if entity @s[tag=aj.lich.bone.hair_side] run function animated_java:lich/variants/default/zzz/apply_to_bone_hair_side
execute on passengers if entity @s[tag=aj.lich.bone.hair_side1] run function animated_java:lich/variants/default/zzz/apply_to_bone_hair_side1
execute on passengers if entity @s[tag=aj.lich.bone.beard] run function animated_java:lich/variants/default/zzz/apply_to_bone_beard
execute on passengers if entity @s[tag=aj.lich.bone.head] run function animated_java:lich/variants/default/zzz/apply_to_bone_head
execute on passengers if entity @s[tag=aj.lich.bone.body] run function animated_java:lich/variants/default/zzz/apply_to_bone_body
execute on passengers if entity @s[tag=aj.lich.bone.left4] run function animated_java:lich/variants/default/zzz/apply_to_bone_left4
execute on passengers if entity @s[tag=aj.lich.bone.left3] run function animated_java:lich/variants/default/zzz/apply_to_bone_left3
execute on passengers if entity @s[tag=aj.lich.bone.aura] run function animated_java:lich/variants/default/zzz/apply_to_bone_aura
execute on passengers if entity @s[tag=aj.lich.bone.scythe] run function animated_java:lich/variants/default/zzz/apply_to_bone_scythe
execute on passengers if entity @s[tag=aj.lich.bone.right2] run function animated_java:lich/variants/default/zzz/apply_to_bone_right2
execute on passengers if entity @s[tag=aj.lich.bone.right1] run function animated_java:lich/variants/default/zzz/apply_to_bone_right1
execute on passengers if entity @s[tag=aj.lich.bone.left_leg] run function animated_java:lich/variants/default/zzz/apply_to_bone_left_leg
execute on passengers if entity @s[tag=aj.lich.bone.right_leg] run function animated_java:lich/variants/default/zzz/apply_to_bone_right_leg
return 1