# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.sword_projectile.root] run return 0
execute on passengers if entity @s[tag=aj.sword_projectile.data] unless data entity @s {data:{rigHash: '7d01739f515f6b71ffb94e3888ce1608c58e9377b9f2717b38ef43228b8f701f'}} on vehicle run function animated_java:sword_projectile/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1