# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.sword_projectile.root] run return 0
execute if entity @s[tag=aj.sword_projectile.animation.spin.playing] run function animated_java:sword_projectile/animations/spin/zzz/on_tick
execute if entity @s[tag=aj.sword_projectile.animation.summon.playing] run function animated_java:sword_projectile/animations/summon/zzz/on_tick
execute on passengers run rotate @s ~ ~