# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_arms_flipped) {transformation: [-0.5f,0f,0f,0f,0f,0.7696f,-0.2558f,0.1356f,0f,0.2427f,-0.7304f,-0.3323f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_arms_rotation) {transformation: [-0.5f,0f,0f,0f,0f,0.7696f,-0.2558f,1.29f,0f,0.2427f,-0.7304f,0.0317f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_wand) {transformation: [-1f,0f,0f,-0.375f,0f,0.3827f,0.9239f,0.8281f,0f,0.9239f,-0.3827f,0.0156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-1f,0f,0f,-0.3125f,0f,1f,0f,1.375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"cast_point":{"posx":-0.359375,"posy":0.5105414106992452,"posz":0.14717242987549958,"roty":0,"rotx":67.50000000000001}}}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:wizard/animations/shield/zzz/frames/24_root_commands