# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:cutter/animations/travel/zzz/apply_frame {frame: 1}
scoreboard players add @s aj.travel.frame 1