# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound minecraft:entity.wind_charge.wind_burst master @a ~ ~ ~ 1.5 0.6
function magic:mobs/hunter/motion/lock_rotation
execute if entity @p[distance=..6] run scoreboard players set #magicMotion magic.temp 2
execute unless entity @p[distance=..6] run scoreboard players set #magicMotion magic.temp 3
function magic:mobs/hunter/motion/launch_diagonal