# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.spin.frame dummy
scoreboard objectives add aj.expand.frame dummy
scoreboard objectives add aj.shrink.frame dummy