# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.dummy.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'dummy', 'function_path': 'animated_java:dummy/animations/pause_all'}
tag @s remove aj.dummy.animation.still.playing
tag @s remove aj.dummy.animation.cast1.playing