# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.shield.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'shield', 'function_path': 'animated_java:shield/animations/summon/next_frame'}
execute if score @s aj.summon.frame matches 15.. run scoreboard players set @s aj.summon.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.summon.frame
execute at @s run function animated_java:shield/animations/summon/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.summon.frame 1