# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.wizard.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'wizard', 'function_path': 'animated_java:wizard/animations/pause_all'}
tag @s remove aj.wizard.animation.die.playing
tag @s remove aj.wizard.animation.still.playing
tag @s remove aj.wizard.animation.walk.playing
tag @s remove aj.wizard.animation.single.playing
tag @s remove aj.wizard.animation.shield.playing
tag @s remove aj.wizard.animation.flury.playing
tag @s remove aj.wizard.animation.blast.playing
tag @s remove aj.wizard.animation.summon.playing
tag @s remove aj.wizard.animation.aggro.playing