# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:ghost_knight rig_hash set value '7c7215a9e975124353e67f13c1c5a6eb36344ae922f11099318f8335e5ae68e6'
scoreboard objectives add aj.spawn.frame dummy
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.move.frame dummy
scoreboard objectives add aj.dodge_back.frame dummy
scoreboard objectives add aj.swing.frame dummy
scoreboard objectives add aj.thrust.frame dummy
scoreboard objectives add aj.block.frame dummy
scoreboard objectives add aj.block_hit.frame dummy