# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.spawn.frame
scoreboard objectives remove aj.idle.frame
scoreboard objectives remove aj.move.frame
scoreboard objectives remove aj.dodge_back.frame
scoreboard objectives remove aj.swing.frame
scoreboard objectives remove aj.thrust.frame
scoreboard objectives remove aj.block.frame
scoreboard objectives remove aj.block_hit.frame
tellraw @a [{color:'gray',text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:'dark_gray',italic:true,text:'\n (animated_java:ghost_knight)'},'\n → ',{color:'green',text:'Successfully uninstalled '},{color:'yellow',text:'ghost_knight'},{color:'green',text:'!'},{color:'gray',italic:true,text:'\n If you have exported multiple times, you may have to remove objectives from previous exports manually, as Animated Java only knows about the objectives from the most recent export.'},'\n']