# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.cutter.root] run return 0
execute on passengers if entity @s[tag=aj.cutter.data] unless data entity @s {data:{rigHash: '493123bb0f9865e45c907b51618752ba1fb951ee681ff476b7a0e4cc8d6a9180'}} on vehicle run function animated_java:cutter/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1