# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound minecraft:entity.fox.screech master @a ~ ~ ~ 5 2
execute on vehicle run function magic:spells/42/damage