# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on vehicle run function magic:spells/42/damage
execute on vehicle run scoreboard players remove @s[scores={slowcast.dist=3..}] slowcast.dist 1