# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hat) {transformation: [-1f,0f,0f,0f,0f,0.9511f,-0.309f,2.0335f,0f,-0.309f,-0.9511f,-0.6567f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_nose) {transformation: [-1f,0f,0f,0f,0f,0.9511f,-0.309f,1.558f,0f,-0.309f,-0.9511f,-0.5022f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9511f,-0.309f,1.4391f,0f,-0.309f,-0.9511f,-0.4635f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.9511f,-0.309f,1.4391f,0f,-0.309f,-0.9511f,-0.4635f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_arms_flipped) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.148f,0f,0f,0f,-0.6515f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_arms_rotation) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.148f,0f,0f,0f,-0.6515f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-1f,0f,0f,0.3125f,0f,0.9511f,-0.309f,1.3202f,0f,-0.309f,-0.9511f,-0.4249f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_wand) {transformation: [-1f,0f,0f,-0.375f,0f,0.9511f,-0.309f,0.8435f,0f,-0.309f,-0.9511f,-0.1222f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-1f,0f,0f,-0.3125f,0f,0.9511f,-0.309f,1.3202f,0f,-0.309f,-0.9511f,-0.4249f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_leg) {transformation: [-1f,0f,0f,0.125f,0f,0.9511f,-0.309f,0.7258f,0f,-0.309f,-0.9511f,-0.2318f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-1f,0f,0f,-0.125f,0f,0.9511f,-0.309f,0.7258f,0f,-0.309f,-0.9511f,-0.2318f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"cast_point":{"posx":-0.35937500000000006,"posy":0.9497737842072891,"posz":0.2047633016137116,"roty":0,"rotx":-18.000000000000007}}}