# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hat) {transformation: [-1f,0f,0f,0f,0f,0.809f,-0.5878f,1.7442f,0f,-0.5878f,-0.809f,-1.249f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_nose) {transformation: [-1f,0f,0f,0f,0f,0.809f,-0.5878f,1.3397f,0f,-0.5878f,-0.809f,-0.9552f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.809f,-0.5878f,1.2385f,0f,-0.5878f,-0.809f,-0.8817f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.809f,-0.5878f,1.2385f,0f,-0.5878f,-0.809f,-0.8817f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_arms_flipped) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.9036f,0f,0f,0f,-0.9705f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_arms_rotation) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.9036f,0f,0f,0f,-0.9705f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-1f,0f,0f,0.3125f,0f,0.809f,-0.5878f,1.1374f,0f,-0.5878f,-0.809f,-0.8082f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_wand) {transformation: [-1f,0f,0f,-0.375f,0f,0.809f,-0.5878f,0.7776f,0f,-0.5878f,-0.809f,-0.373f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-1f,0f,0f,-0.3125f,0f,0.809f,-0.5878f,1.1374f,0f,-0.5878f,-0.809f,-0.8082f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_leg) {transformation: [-1f,0f,0f,0.125f,0f,0.809f,-0.5878f,0.6318f,0f,-0.5878f,-0.809f,-0.4408f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-1f,0f,0f,-0.125f,0f,0.809f,-0.5878f,0.6318f,0f,-0.5878f,-0.809f,-0.4408f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"cast_point":{"posx":-0.359375,"posy":0.97967568004592,"posz":-0.09489205540433904,"roty":0,"rotx":-36}}}