# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hat) {transformation: [-1f,0f,0f,0f,0f,0.5878f,-0.809f,1.2865f,0f,-0.809f,-0.5878f,-1.7192f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_nose) {transformation: [-1f,0f,0f,0f,0f,0.5878f,-0.809f,0.9927f,0f,-0.809f,-0.5878f,-1.3147f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.5878f,-0.809f,0.9192f,0f,-0.809f,-0.5878f,-1.2135f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.5878f,-0.809f,0.9192f,0f,-0.809f,-0.5878f,-1.2135f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_arms_flipped) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.5732f,0f,0f,0f,-1.1945f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_arms_rotation) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.5732f,0f,0f,0f,-1.1945f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-1f,0f,0f,0.3125f,0f,0.5878f,-0.809f,0.8457f,0f,-0.809f,-0.5878f,-1.1124f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_wand) {transformation: [-1f,0f,0f,-0.375f,0f,0.5878f,-0.809f,0.638f,0f,-0.809f,-0.5878f,-0.5873f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-1f,0f,0f,-0.3125f,0f,0.5878f,-0.809f,0.8457f,0f,-0.809f,-0.5878f,-1.1124f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_leg) {transformation: [-1f,0f,0f,0.125f,0f,0.5878f,-0.809f,0.4783f,0f,-0.809f,-0.5878f,-0.6068f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-1f,0f,0f,-0.125f,0f,0.5878f,-0.809f,0.4783f,0f,-0.809f,-0.5878f,-0.6068f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"cast_point":{"posx":-0.35937499999999994,"posy":0.9161272687050694,"posz":-0.3852587168875866,"roty":0,"rotx":-54.00000000000001}}}