# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hat) {transformation: [-1f,0f,0f,0f,0f,0.309f,-0.9511f,0.7067f,0f,-0.9511f,-0.309f,-2.021f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_nose) {transformation: [-1f,0f,0f,0f,0f,0.309f,-0.9511f,0.5522f,0f,-0.9511f,-0.309f,-1.5455f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.309f,-0.9511f,0.5135f,0f,-0.9511f,-0.309f,-1.4266f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.309f,-0.9511f,0.5135f,0f,-0.9511f,-0.309f,-1.4266f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_arms_flipped) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.1903f,0f,0f,0f,-1.3016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_arms_rotation) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.1903f,0f,0f,0f,-1.3016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-1f,0f,0f,0.3125f,0f,0.309f,-0.9511f,0.4749f,0f,-0.9511f,-0.309f,-1.3077f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_wand) {transformation: [-1f,0f,0f,-0.375f,0f,0.309f,-0.9511f,0.4396f,0f,-0.9511f,-0.309f,-0.7441f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-1f,0f,0f,-0.3125f,0f,0.309f,-0.9511f,0.4749f,0f,-0.9511f,-0.309f,-1.3077f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_leg) {transformation: [-1f,0f,0f,0.125f,0f,0.309f,-0.9511f,0.2818f,0f,-0.9511f,-0.309f,-0.7133f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-1f,0f,0f,-0.125f,0f,0.309f,-0.9511f,0.2818f,0f,-0.9511f,-0.309f,-0.7133f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"cast_point":{"posx":-0.3593749999999999,"posy":0.7665726985472183,"posz":-0.6379135709065589,"roty":0,"rotx":-72.00000000000001}}}