# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:sword_projectile rig_hash set value '5e8e7443f104f13793355f071572e2ab5ffffb75214aac5a1a082ffec7b847cf'
scoreboard objectives add aj.spin.frame dummy
scoreboard objectives add aj.summon.frame dummy