# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:sword_projectile rig_hash set value '9c8a862dd5c5fb266dc136246955513b402a49c263b8633cb5494930f9aa09f4'
scoreboard objectives add aj.spin.frame dummy
scoreboard objectives add aj.summon.frame dummy