# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_right_leg1) {transformation: [-1f,0f,0f,-0.1562f,0f,0.887f,0.4617f,-0.1773f,0f,0.4617f,-0.887f,-0.3391f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-1f,0f,0f,-0.1562f,0f,0.887f,0.4617f,-0.011f,0f,0.4617f,-0.887f,-0.2525f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_leg1) {transformation: [-1f,0f,0f,0.1563f,0f,0.887f,0.4617f,-0.1773f,0f,0.4617f,-0.887f,-0.3391f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_leg) {transformation: [-1f,0f,0f,0.1563f,0f,0.887f,0.4617f,-0.011f,0f,0.4617f,-0.887f,-0.2525f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tail) {transformation: [-1f,0f,0f,-0.0312f,0f,0.999f,-0.0436f,0.0948f,0f,-0.0436f,-0.999f,-0.695f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9962f,0.0872f,0.2192f,0f,0.0872f,-0.9962f,0.3631f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing1) {transformation: [-1f,0f,0f,-1.0977f,0f,0.999f,-0.0436f,0.3256f,0f,-0.0436f,-0.999f,0.202f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-1f,0f,0f,-0.2653f,0f,0.999f,-0.0436f,0.3044f,0f,-0.0436f,-0.999f,-0.1341f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing1) {transformation: [-1f,0f,0f,1.0977f,0f,0.999f,-0.0436f,0.3256f,0f,-0.0436f,-0.999f,0.202f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-1f,0f,0f,0.2653f,0f,0.999f,-0.0436f,0.3044f,0f,-0.0436f,-0.999f,-0.1341f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0.0313f,0f,0.999f,-0.0436f,-0.0625f,0f,-0.0436f,-0.999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}