# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.wizard.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'wizard', 'function_path': 'animated_java:wizard/animations/single/stop'}
tag @s remove aj.wizard.animation.single.playing
scoreboard players set @s aj.single.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:wizard/animations/single/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only