# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '3429a952c224ed4f4c3fcca072a69e4a3a21cc32c0947448653f9aa503aa4976'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack