# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp args.uuid set from entity @s data.uuids.locator_hitbox
function animated_java:lich/zzz/as_all_locators/execute_as_uuid with storage aj:temp args
data modify storage aj:temp args.uuid set from entity @s data.uuids.locator_hitbox2
function animated_java:lich/zzz/as_all_locators/execute_as_uuid with storage aj:temp args