# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.lightning.root] run return 0
execute on passengers if entity @s[tag=aj.lightning.data] unless data entity @s {data:{rigHash: '95d3d8114502b6e8ca7e9a62f95c76610839104bb43973bfda458628e9c09a6b'}} on vehicle run function animated_java:lightning/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1