# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.lightning.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.lightning.animation.strike.playing] run function animated_java:lightning/animations/strike/zzz/on_tick
execute on passengers if entity @s[tag=aj.lightning.data] run function animated_java:lightning/root/zzz/on_tick/locators_and_cameras
execute at @s on passengers run rotate @s ~ ~