# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players operation #magicSearch magic.id = @s magic.id
scoreboard players set @n[type=wither_skeleton,predicate=magic:match_id,distance=..5] magic.atkCD 40