# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.laceration.root] run return 0
execute on passengers if entity @s[tag=aj.laceration.data] unless data entity @s {data:{rigHash: '318c30ff7ec88145d5a27d0cd2f6bd8c6f89ec0256039b10f2c127a847ae92f9'}} on vehicle run function animated_java:laceration/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1