# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hair_side) {transformation: [-1f,0f,0f,-0.2969f,0f,1f,0.0044f,1.9107f,0f,0.0044f,-1f,0.2542f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hair_side1) {transformation: [-1f,0f,0f,0.2969f,0f,1f,0.0044f,1.9107f,0f,0.0044f,-1f,0.2542f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_beard) {transformation: [-1f,0f,0f,0f,0f,0.9998f,-0.0175f,1.5921f,0f,-0.0175f,-0.9998f,0.2601f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.984f,0.1779f,1.7344f,0f,0.1779f,-0.984f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.1237f,0f,-0.054f,0f,0f,1.125f,0f,1.0625f,0.054f,0f,-1.1237f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left4) {transformation: [-0.9763f,-0.2164f,0f,0.3598f,-0.2164f,0.9763f,0f,1.1614f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left3) {transformation: [-0.9763f,-0.2164f,0f,0.2915f,-0.2164f,0.9763f,0f,0.026f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_scythe) {transformation: [-1.705f,-0.0539f,-0.0928f,-0.8555f,-0.0463f,1.7021f,-0.1377f,1.2062f,0.0968f,-0.135f,-1.7002f,0.0592f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right2) {transformation: [-0.0599f,0.9973f,0.0418f,-0.5273f,-0.099f,0.0357f,-0.9944f,1.2195f,-0.9933f,-0.0637f,0.0966f,0.0538f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-0.7042f,0.7075f,-0.0599f,-1.059f,0.7095f,0.6977f,-0.099f,0.2564f,-0.0283f,-0.1123f,-0.9933f,0.1819f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:lich/animations/cast2/zzz/frames/53_root_commands