# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hair_side) {transformation: [-1f,0f,0f,-0.2969f,0f,1f,0f,-0.5257f,0f,0f,-1f,0.2534f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hair_side1) {transformation: [-1f,0f,0f,0.2969f,0f,1f,0f,-0.5257f,0f,0f,-1f,0.2534f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_beard) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.8443f,0f,0f,-1f,0.2607f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9848f,0.1736f,-0.7031f,0f,0.1736f,-0.9848f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.125f,0f,0f,0f,0f,1.125f,0f,-1.375f,0f,0f,-1.125f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left4) {transformation: [-0.9763f,-0.2164f,0f,0.3598f,-0.2164f,0.9763f,0f,-1.2761f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left3) {transformation: [-0.9763f,-0.2164f,0f,0.2915f,-0.2164f,0.9763f,0f,-2.4115f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_aura) {transformation: [-2.375f,0f,0f,-2.1639f,0f,2.375f,0f,-0.2447f,0f,0f,-2.375f,-0.0156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_scythe) {transformation: [-1.7083f,0f,0f,-0.8514f,0f,1.7083f,0f,-1.2447f,0f,0f,-1.7083f,-0.0156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right2) {transformation: [0f,0.999f,0.0436f,-0.5236f,0f,0.0436f,-0.999f,-1.2304f,-1f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-0.7373f,0.6756f,0f,-1.011f,0.6756f,0.7373f,0f,-2.2249f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"scythe_blade":{"posx":-1.5233096375864408,"posy":-0.10408677923241516,"posz":-0.015625000000000274,"roty":2.842170943040401e-14,"rotx":5.588124107419383e-16},"scythe_pole":{"posx":-0.8358096375864408,"posy":-1.0415867792324147,"posz":-0.015625000000000076,"roty":2.842170943040401e-14,"rotx":5.588124107419383e-16}}}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:lich/animations/slam/zzz/frames/44_root_commands