# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.wizard.root] run return 0
execute on passengers if entity @s[tag=aj.wizard.data] unless data entity @s {data:{rigHash: '583992b5023dc953e39843706ef4551ba9248cc6cd22cac934a6a2d92b8c8d7f'}} on vehicle run function animated_java:wizard/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1