# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.wizard.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.wizard.animation.die.playing] run function animated_java:wizard/animations/die/zzz/on_tick
execute if entity @s[tag=aj.wizard.animation.still.playing] run function animated_java:wizard/animations/still/zzz/on_tick
execute if entity @s[tag=aj.wizard.animation.walk.playing] run function animated_java:wizard/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.wizard.animation.single.playing] run function animated_java:wizard/animations/single/zzz/on_tick
execute if entity @s[tag=aj.wizard.animation.shield.playing] run function animated_java:wizard/animations/shield/zzz/on_tick
execute if entity @s[tag=aj.wizard.animation.flury.playing] run function animated_java:wizard/animations/flury/zzz/on_tick
execute if entity @s[tag=aj.wizard.animation.blast.playing] run function animated_java:wizard/animations/blast/zzz/on_tick
execute if entity @s[tag=aj.wizard.animation.summon.playing] run function animated_java:wizard/animations/summon/zzz/on_tick
execute if entity @s[tag=aj.wizard.animation.aggro.playing] run function animated_java:wizard/animations/aggro/zzz/on_tick
execute on passengers if entity @s[tag=aj.wizard.data] run function animated_java:wizard/root/zzz/on_tick/locators_and_cameras
execute at @s on passengers run rotate @s ~ ~
execute as @s run scoreboard players operation #magicSearch magic.id = @s magic.id
execute as @s[tag=!aj.wizard.animation.die.playing] at @s unless entity @e[type=wandering_trader,tag=wizBase,predicate=magic:match_id] run function animated_java:wizard/animations/die/play