# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function magic:mobs/hunter/dodge/end_dodge
execute on vehicle run function magic:mobs/hunter/dodge/dash_chance