# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hat) {transformation: [-1f,0f,0f,0f,0f,1f,0f,2.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_nose) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-0.7312f,-0.6821f,0f,0.3125f,-0.6821f,0.7312f,0f,1.375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_wand) {transformation: [-0.9976f,-0.0126f,0.0685f,-0.4027f,-0.0232f,0.9875f,-0.1561f,1.4117f,-0.0657f,-0.1574f,-0.9854f,0.542f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-0.9985f,0.0503f,0.0196f,-0.3125f,-0.0217f,-0.041f,-0.9989f,1.375f,-0.0495f,-0.9979f,0.042f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"cast_point":{"posx":-0.4106971591726917,"posy":1.4657235043502943,"posz":0.8817156618133395,"roty":3.9780611468017355,"rotx":-8.983348850576377}}}