# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players operation #magicSearch magic.id = @s magic.id
tag @n[type=wandering_trader,tag=wizBase,predicate=magic:match_id] remove inAtk