# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function magic:mobs/hunter/motion/lock_rotation
execute if entity @p[distance=..3.5] run scoreboard players set #magicMotion magic.temp 1
execute unless entity @p[distance=..3.5] run scoreboard players set #magicMotion magic.temp 2
playsound minecraft:entity.player.attack.sweep master @a ~ ~ ~ 1 1.6
function magic:mobs/hunter/motion/launch