# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.dummy.root] run return 0
execute on passengers if entity @s[tag=aj.dummy.data] unless data entity @s {data:{rigHash: '491a5aec5e7c0d515c25c530626dbe12cb88e30c6e90dee557ecf4ec53b10889'}} on vehicle run function animated_java:dummy/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1