# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.dummy.root] run return 0
execute on passengers if entity @s[tag=aj.dummy.data] unless data entity @s {data:{rigHash: 'cb1534592e7902c2b139f7cf4337309589a5b1963e0aaca55a9a574b9777ac84'}} on vehicle run function animated_java:dummy/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1