# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.dummy.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.dummy.animation.still.playing] run function animated_java:dummy/animations/still/zzz/on_tick
execute if entity @s[tag=aj.dummy.animation.cast1.playing] run function animated_java:dummy/animations/cast1/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~
function magic:mobs/dummy/detect_death