# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound minecraft:entity.player.attack.strong master @a ~ ~ ~ 2 0.8
execute if entity @p[distance=..4] run scoreboard players set #magicMotion magic.temp 2
execute unless entity @p[distance=..4] run scoreboard players set #magicMotion magic.temp 3
function magic:mobs/hunter/motion/launch