# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.mage_hunter.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'mage_hunter', 'function_path': 'animated_java:mage_hunter/animations/pause_all'}
tag @s remove aj.mage_hunter.animation.still.playing
tag @s remove aj.mage_hunter.animation.die.playing
tag @s remove aj.mage_hunter.animation.stagger.playing
tag @s remove aj.mage_hunter.animation.walk.playing
tag @s remove aj.mage_hunter.animation.transition_phase.playing
tag @s remove aj.mage_hunter.animation.slash.playing
tag @s remove aj.mage_hunter.animation.double_slash.playing
tag @s remove aj.mage_hunter.animation.cross_slash.playing
tag @s remove aj.mage_hunter.animation.thrust1.playing
tag @s remove aj.mage_hunter.animation.thrust2.playing
tag @s remove aj.mage_hunter.animation.lunge1.playing
tag @s remove aj.mage_hunter.animation.side_slash1.playing
tag @s remove aj.mage_hunter.animation.side_slash2.playing
tag @s remove aj.mage_hunter.animation.dodge_back.playing
tag @s remove aj.mage_hunter.animation.dodge_front.playing
tag @s remove aj.mage_hunter.animation.dodge_right.playing
tag @s remove aj.mage_hunter.animation.dodge_left.playing