# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:hellfire/animations/pause_all
tag @s add aj.hellfire.animation.start.playing
scoreboard players set @s aj.start.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:hellfire/animations/start/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only