# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hair_side) {transformation: [-1f,0f,0f,-0.2969f,0f,0f,-1f,0.4409f,0f,-1f,0f,-1.9118f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hair_side1) {transformation: [-1f,0f,0f,0.2969f,0f,0f,-1f,0.4409f,0f,-1f,0f,-1.9118f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_beard) {transformation: [-1f,0f,0f,0f,0f,0f,-1f,0.4482f,0f,-1f,0f,-1.5932f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.1736f,-0.9848f,0.1875f,0f,-0.9848f,-0.1736f,-1.7344f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.125f,0f,0f,0f,0f,0f,-1.125f,0.1875f,0f,-1.125f,0f,-1.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left4) {transformation: [-0.9763f,-0.2164f,0f,0.3598f,0f,0f,-1f,0.1875f,0.2164f,-0.9763f,0f,-1.1614f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left3) {transformation: [-0.9763f,-0.2164f,0f,0.2915f,0f,0f,-1f,0.1875f,0.2164f,-0.9763f,0f,-0.026f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_scythe) {transformation: [-1.7083f,0f,0f,-0.8514f,0f,0f,-1.7083f,0.1719f,0f,-1.7083f,0f,-1.1928f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right2) {transformation: [0f,0.999f,0.0436f,-0.5236f,-1f,0f,0f,0.1875f,0f,-0.0436f,0.999f,-1.2071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-0.7373f,0.6756f,0f,-1.011f,0f,0f,-1f,0.1875f,-0.6756f,-0.7373f,0f,-0.2126f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_leg) {transformation: [-1f,0f,0f,0.125f,0f,0f,-1f,0.1813f,0f,-1f,0f,-0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-1f,0f,0f,-0.125f,0f,0f,-1f,0.1813f,0f,-1f,0f,-0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"hitbox":{"posx":-0.8983096375864406,"posy":0.17187500000000064,"posz":-2.3334132207675853,"roty":360,"rotx":-90},"hitbox2":{"posx":-1.6483096375864406,"posy":0.17187500000000042,"posz":-2.3334132207675853,"roty":360,"rotx":-90}}}