# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound minecraft:entity.player.attack.weak master @a ~ ~ ~ 3 1.2
function magic:mobs/hunter/motion/lock_rotation
execute if entity @p[distance=..4] run scoreboard players set #magicMotion magic.temp 1
execute unless entity @p[distance=..4] run scoreboard players set #magicMotion magic.temp 2
function magic:mobs/hunter/motion/launch