# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.ghost_knight.animation.spawn.playing
tag @s remove aj.ghost_knight.animation.idle.playing
tag @s remove aj.ghost_knight.animation.move.playing
tag @s remove aj.ghost_knight.animation.dodge_back.playing
tag @s remove aj.ghost_knight.animation.swing.playing
tag @s remove aj.ghost_knight.animation.thrust.playing
tag @s remove aj.ghost_knight.animation.block.playing
tag @s remove aj.ghost_knight.animation.block_hit.playing