# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.lich.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'lich', 'function_path': 'animated_java:lich/variants/scythe_aura/apply'}
execute on passengers if entity @s[tag=aj.lich.bone.aura] run function animated_java:lich/variants/scythe_aura/zzz/apply_to_bone_aura
execute on passengers if entity @s[tag=aj.lich.bone.scythe] run function animated_java:lich/variants/scythe_aura/zzz/apply_to_bone_scythe
return 1