# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_chest) {transformation: [-1f,0f,0f,0f,0f,0.999f,-0.0436f,-0.7187f,0f,-0.0436f,-0.999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cape) {transformation: [-1f,0f,0f,0.2188f,0f,0.9962f,0.0872f,-0.5937f,0f,0.0872f,-0.9962f,-0.0844f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_saber) {transformation: [-1.349f,-0.2379f,0.1198f,-0.4126f,0.118f,0.0208f,1.3698f,-1.1752f,-0.2388f,1.3541f,0f,0.0121f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_forearm) {transformation: [-0.9811f,0.0872f,0.173f,-0.399f,0.0858f,0.9962f,-0.0151f,-0.863f,-0.1736f,0f,-0.9848f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-0.9962f,0.0872f,0f,-0.25f,0.0872f,0.9962f,0f,-0.5937f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_short_sword) {transformation: [-1.1523f,0.1517f,-0.1017f,0.423f,-0.1008f,0.0133f,1.1622f,-1.1215f,0.1523f,1.1567f,0f,0.0103f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_forearm) {transformation: [-0.9877f,-0.0872f,-0.13f,0.399f,-0.0864f,0.9962f,-0.0114f,-0.863f,0.1305f,0f,-0.9914f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-0.9962f,-0.0872f,0f,0.25f,-0.0872f,0.9962f,0f,-0.5937f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_torso) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.9531f,0f,0f,-1f,-0.0031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_dress) {transformation: [-0.9763f,-0.2164f,0f,-0.1936f,-0.2164f,0.9763f,0f,-1.1099f,0f,0f,-1f,-0.0078f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_dress) {transformation: [-0.9763f,0.2164f,0f,0.1311f,0.2164f,0.9763f,0f,-1.1099f,0f,0f,-1f,-0.0078f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lower_right_leg) {transformation: [-0.999f,0.0436f,0f,-0.1414f,0.0436f,0.999f,0f,-1.5934f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-0.999f,0.0436f,0f,-0.125f,0.0436f,0.999f,0f,-1.2187f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lower_left_leg) {transformation: [-0.999f,-0.0436f,0f,0.1414f,-0.0436f,0.999f,0f,-1.5934f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_leg) {transformation: [-0.999f,-0.0436f,0f,0.125f,-0.0436f,0.999f,0f,-1.2187f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_waist) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pony_tail) {transformation: [-1f,0f,0f,0f,0f,0.9962f,0.0872f,-0.4484f,0f,0.0872f,-0.9962f,-0.2308f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9962f,0.0872f,-0.5f,0f,0.0872f,-0.9962f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:mage_hunter/animations/dodge_front/zzz/frames/10_root_commands