# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.mage_hunter.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'mage_hunter', 'function_path': 'animated_java:mage_hunter/animations/side_slash1/next_frame'}
execute if score @s aj.side_slash1.frame matches 27.. run scoreboard players set @s aj.side_slash1.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.side_slash1.frame
execute at @s run function animated_java:mage_hunter/animations/side_slash1/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.side_slash1.frame 1