# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.new
function animated_java:global/internal/gu/convert_uuid_array_to_string
tp @s ^-0.5691132931 ^0.3521832726 ^1.3080055722 ~270 ~12.5