# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function magic:mobs/lich/atk/stop_movement
execute unless entity @p[distance=..3.4] run function magic:mobs/lich/atk/medium_launch
execute if entity @p[distance=..3.4] run function magic:mobs/lich/atk/small_launch
function magic:mobs/lich/atk/lock_rotation