# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.dummy.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'dummy', 'function_path': 'animated_java:dummy/animations/still/stop'}
tag @s remove aj.dummy.animation.still.playing
scoreboard players set @s aj.still.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:dummy/animations/still/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only